"""Constants for the CCTV Relay integration."""

from homeassistant.const import Platform

DOMAIN = "cctv_relay"
PLATFORMS = (Platform.SENSOR,)

CONF_SYNOLOGY_URL = "synology_url"
CONF_VERIFY_SSL = "verify_ssl"
CONF_CAMERA_IDS = "camera_ids"
CONF_TELEGRAM_NOTIFY_ENTITY = "telegram_notify_entity"
CONF_WEBHOOK_ID = "webhook_id"
CONF_PRE_SECONDS = "pre_seconds"
CONF_POST_SECONDS = "post_seconds"
CONF_HISTORY_ENABLED = "history_enabled"
CONF_HISTORY_INTERVAL = "history_interval"
CONF_HISTORY_LOOKBACK = "history_lookback"
CONF_HISTORY_PAGE_SIZE = "history_page_size"
CONF_MATCH_WINDOW = "match_window"
CONF_MAX_CLIP_MEGABYTES = "max_clip_megabytes"
CONF_FFMPEG_PATH = "ffmpeg_path"


DEFAULT_PRE_SECONDS = 3
DEFAULT_POST_SECONDS = 5
MAX_PRE_SECONDS = 15
MAX_POST_SECONDS = 30
MAX_CLIP_SECONDS = 30
DEFAULT_VERIFY_SSL = True
DEFAULT_HISTORY_ENABLED = True
DEFAULT_HISTORY_INTERVAL = 60
DEFAULT_HISTORY_LOOKBACK = 172800
DEFAULT_HISTORY_PAGE_SIZE = 200
DEFAULT_MATCH_WINDOW = 15
DEFAULT_MAX_CLIP_MEGABYTES = 45
DEFAULT_FFMPEG_PATH = "/usr/bin/ffmpeg"
DEFAULT_INDEX_GRACE_SECONDS = 1
DEFAULT_RETRY_BASE_SECONDS = 1.0
DEFAULT_RETRY_MAX_SECONDS = 300.0
DEFAULT_MAX_RETRY_ATTEMPTS = 20
DEFAULT_MAX_ACTIVE_EVENTS = 1000
DEFAULT_WEBHOOK_RATE_LIMIT = 120
DEFAULT_WEBHOOK_RATE_WINDOW_SECONDS = 60
DEFAULT_SENT_RETENTION_DAYS = 30
DEFAULT_DEDUP_WINDOW_SECONDS = 3
DEFAULT_DSM_TIMEOUT_SECONDS = 20
DEFAULT_EXPORT_TIMEOUT_SECONDS = 120


ALLOWED_EVENT_TYPES = frozenset({"motion", "lost", "restored"})
SIGNAL_QUEUE_UPDATED = f"{DOMAIN}_queue_updated"
